#! /usr/bin/env bash

base="$2"
new="$3"
cwd=`pwd`

stamp=patch_`date "+%Y%m%d%H%M%S"`

cd $1

diff -rupN -x SKA -x build -x aclocal.m4 -x autom4te.cache -x configure \
	$base/ $new/ | sed '/Binary\ files\ /d' > $cwd/$stamp

cp $cwd/$stamp $cwd/patch_current
